// <auto-generated />
using ASI.MiniModelagem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASI.MiniModelagem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ASI.MiniModelagem.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Departamento de Engenharias e Computação",
                            Sigla = "DEC"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Departamento de Ciências Exatas",
                            Sigla = "DCEX"
                        });
                });

            modelBuilder.Entity("ASI.MiniModelagem.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Professores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 1,
                            Nome = "Larissa"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 2,
                            Nome = "Gabriel"
                        });
                });

            modelBuilder.Entity("ASI.MiniModelagem.Models.ProfessorProjeto", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfessorId", "ProjetoId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("ProfessoresProjetos", (string)null);

                    b.HasData(
                        new
                        {
                            ProfessorId = 1,
                            ProjetoId = 1
                        },
                        new
                        {
                            ProfessorId = 2,
                            ProjetoId = 1
                        });
                });

            modelBuilder.Entity("ASI.MiniModelagem.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projetos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Projeto ASI"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Projeto math"
                        });
                });

            modelBuilder.Entity("ASI.MiniModelagem.Models.Professor", b =>
                {
                    b.HasOne("ASI.MiniModelagem.Models.Departamento", "Departamento")
                        .WithMany("Professores")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ASI.MiniModelagem.Models.ProfessorProjeto", b =>
                {
                    b.HasOne("ASI.MiniModelagem.Models.Professor", "Professor")
                        .WithMany("ProfessoresProjetos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASI.MiniModelagem.Models.Projeto", "Projeto")
                        .WithMany("ProfessoresProjetos")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("ASI.MiniModelagem.Models.Departamento", b =>
                {
                    b.Navigation("Professores");
                });

            modelBuilder.Entity("ASI.MiniModelagem.Models.Professor", b =>
                {
                    b.Navigation("ProfessoresProjetos");
                });

            modelBuilder.Entity("ASI.MiniModelagem.Models.Projeto", b =>
                {
                    b.Navigation("ProfessoresProjetos");
                });
#pragma warning restore 612, 618
        }
    }
}
